#!/usr/bin/env bash
# Installs Nginx and configures it to listen on port 80
# Prints "Hello World"

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create a simple "Hello World" index page
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Start Nginx service
sudo service nginx start

echo "Nginx installed and configured. You can now access the server."

exit 0
