#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update the package list
apt-get update

# Install Nginx
apt-get install nginx -y

# Create a basic "Hello World!" index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Add a URL rewrite rule to Nginx configuration
nginx_config="/etc/nginx/sites-available/default"
rewrite_rule="rewrite ^/redirect_me https://www.w3schools.com/;"
sed -i "46i $rewrite_rule" "$nginx_config"

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
error_page_config="error_page 404 /custom_404.html;"
sed -i "46i $error_page_config" "$nginx_config"

# Restart Nginx to apply the changes
service nginx restart
