#!/usr/bin/env bash
# This script pings an IP address  passed as an argument five times.

if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ip_address=$1
  ping -c 5 "$ip_address"
fi
