#!/usr/bin/env bash
# This script is for fixing Nginx to listen on port 80.

sites_enabled="/etc/nginx/sites-enabled"
default_config="default"

# Ensure the sites-enabled directory exists
[ -d "$sites_enabled" ] || exit 1

# Remove the existing 'default' symbolic link
rm -f "$sites_enabled/$default_config"

# Create a new symbolic link to the default configuration
ln -s "/etc/nginx/sites-available/$default_config" "$sites_enabled/$default_config"

# Restart Nginx to apply the changes
service nginx restart
