#!/usr/bin/env bash
# Bash script to display content of /etc/passwd with custom formatting

while IFS=':' read -r username _ uid gid info home shell; do
    read -r _ passcode _ <<< "$info"
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $username"
done < /etc/passwd
