#!/usr/bin/env bash
# Check if the school file exists

file_path="school"

if [ -e "$file_path" ]; then
    echo "school file exists"

    # Check if the school file is empty
    if [ -s "$file_path" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the school file is a regular file
    if [ -f "$file_path" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
