#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:22, 443, 80

# Install UFW
apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22)
ufw allow 22/tcp

# Allow HTTPS (port 443)
ufw allow 443/tcp

# Allow HTTP (port 80)
ufw allow 80/tcp

# Enable UFW
ufw --force enable
